name: Docker Image
on:
  push:
    branches:
      - "master"
      - "try-ci"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Env
        id: vars
        shell: bash
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "${GITHUB_ENV}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bohrasd
          password: dckr_pat_JsYCywb1v3gB5utcnMbL3DOWkDQ
      - name: Build images
        shell: bash
        run: |
          IMAGE_TAG="${{ env.SHA_SHORT }}" make docker

          docker tag oryd/kratos:${{ env.SHA_SHORT }} bohrasd/kratos:${{ env.SHA_SHORT }}

          docker push bohrasd/kratos:${{ env.SHA_SHORT }}
